import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0e0e0e] py-12 px-4" style={{ fontFamily: "'Courier New', monospace" }}>
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="font-mono text-sm text-white/50 hover:text-white transition-colors">
          ← Back
        </Link>

        <h1 className="text-2xl font-bold text-white uppercase tracking-widest mt-6 mb-8">
          Terms of Service
        </h1>

        <p className="text-xs text-white/30 mb-8">Last updated: March 31, 2026</p>

        <div className="space-y-6 text-sm text-white/70 leading-relaxed">
          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Agreement</h2>
            <p>
              By creating an account or using BLK Exchange, you agree to these Terms of Service
              and our Privacy Policy. If you do not agree, do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Age Requirement</h2>
            <p>
              You must be at least 13 years old to use BLK Exchange. If you are under 13, you
              may only use BLK Exchange with verifiable parental consent. If you are under 18,
              you represent that your parent or legal guardian has reviewed and agreed to these
              terms on your behalf.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Educational Purpose</h2>
            <p>
              BLK Exchange is a financial literacy education tool. It is a simulation using
              fictional companies and simulated market data. No real money, real securities,
              or real financial transactions are involved. The platform is designed to teach
              investing concepts through gameplay.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Not Financial Advice</h2>
            <p>
              Nothing on BLK Exchange constitutes investment advice, financial advice, trading
              advice, or any other kind of professional advice. AI-generated coaching, debriefs,
              and market commentary are educational content only. The mention of real companies
              (in The Real Exchange feature) is for educational context and does not constitute
              a recommendation to buy or sell any real security. Always consult a licensed
              financial advisor before making real investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Fictional Companies</h2>
            <p>
              The 36 companies traded on BLK Exchange (CROWN, KICKS, DRIP, VIZN, VAULT, etc.)
              are entirely fictional. Any resemblance to real companies is for educational
              illustration purposes. Simulated stock prices, market events, and news headlines
              are generated by AI and do not represent real market activity.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Your Account</h2>
            <p>
              You are responsible for maintaining the security of your account. Do not share
              your login credentials. You may request deletion of your account and data at any
              time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 mt-2">
              <li>Use BLK Exchange for any illegal purpose</li>
              <li>Attempt to manipulate the simulation, leaderboards, or other game mechanics</li>
              <li>Scrape, reverse-engineer, or extract data from the platform</li>
              <li>Create multiple accounts to gain unfair advantages</li>
              <li>Use the platform to provide financial advice to others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">AI-Generated Content</h2>
            <p>
              BLK Exchange uses AI services (Claude by Anthropic, Groq, ElevenLabs) to generate
              market events, portfolio coaching, session debriefs, and voice narration.
              AI-generated content may contain inaccuracies. It is provided for educational
              purposes only and should not be relied upon for real financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Availability</h2>
            <p>
              BLK Exchange is provided as-is. We do not guarantee uninterrupted service. The
              platform may be modified, updated, or discontinued at any time. Simulated
              portfolio values may reset during updates or seasonal resets.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Limitation of Liability</h2>
            <p>
              BLK Exchange and its creator are not liable for any financial losses incurred
              from real investment decisions made based on concepts learned through the
              simulation. The platform is for education only. Use at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Changes</h2>
            <p>
              We may update these terms at any time. Continued use of BLK Exchange after
              changes constitutes acceptance. Material changes will be communicated through
              the platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-white uppercase tracking-wider mb-2">Contact</h2>
            <p>
              Tarik Moody<br />
              blkexchange.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
